# Generated by Django 6.0.4 on 2026-04-13 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points_reward', models.IntegerField(default=10)),
                ('goal_target', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='ecopoint',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ecopoint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ecopoint',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ecopoint',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ecopoint',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('eco_rank', models.CharField(default='Guardian', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
